### ISSUE TITLE
Bayes people tracker crashes

### ISSUE THREAD

**Issue by ferdianjovan** [strands-project/strands_perception_people#112]
I tried using different leg detectors from https://github.com/marcobecerrap/leg_detector
and changed default.yaml to (this is just part of default.yaml)

```
leg_detector:                                          
            topic: "/leg_detector_topic"               
            noise_model:
                velocity:                                      
                    x: 1.4
                    y: 1.4
                position:                                      
                    x: 0.2
                    y: 0.2
            matching_algorithm: "NNJPDA"

```

as the leg_detector already publishes geometry_msgs/PoseArray.
I got an error as follows:

```

PARAMETERS
 * /bayes_people_tracker/detectors/leg_detector/matching_algorithm
 * /bayes_people_tracker/detectors/leg_detector/noise_model/position/x
 * /bayes_people_tracker/detectors/leg_detector/noise_model/position/y
 * /bayes_people_tracker/detectors/leg_detector/noise_model/velocity/x
 * /bayes_people_tracker/detectors/leg_detector/noise_model/velocity/y
 * /bayes_people_tracker/detectors/leg_detector/topic
 * /bayes_people_tracker/detectors/upper_body_detector/matching_algorithm
 * /bayes_people_tracker/detectors/upper_body_detector/noise_model/position/x
 * /bayes_people_tracker/detectors/upper_body_detector/noise_model/position/y
 * /bayes_people_tracker/detectors/upper_body_detector/noise_model/velocity/x
 * /bayes_people_tracker/detectors/upper_body_detector/noise_model/velocity/y
 * /bayes_people_tracker/detectors/upper_body_detector/topic
 * /bayes_people_tracker/marker
 * /bayes_people_tracker/positions
 * /bayes_people_tracker/target_frame
 * /rosdistro
 * /rosversion

NODES
  /
    bayes_people_tracker (bayes_people_tracker/bayes_people_tracker)

ROS_MASTER_URI=http://bob:11311

core service [/rosout] found
process[bayes_people_tracker-1]: started with pid [7793]
[ INFO] [1415731003.888882531]: Found detector: leg_detector ==> [matching_algorithm:NNJPDA,noise_model:[position:[x:0.2,y:0.2],velocity:[x:1.4,y:1.4]],topic:/leg_detector_topic]
[ INFO] [1415731003.888994471]: Adding detector model for: leg_detector.
[ INFO] [1415731003.889096336]: Found detector: upper_body_detector ==> [matching_algorithm:NNJPDA,noise_model:[position:[x:1.2,y:1.2],velocity:[x:1.4,y:1.4]],topic:/upper_body_detector/bounding_box_centres]
[ INFO] [1415731003.889140320]: Adding detector model for: upper_body_detector.
bayes_people_tracker: /home/strands/ferdi_ws/src/strands_perception_people/bayes_people_tracker/include/people_tracker/simple_tracking.h:57: bool MTRK::initialize(FilterType*&, MTRK::sequence_t&) [with FilterType = EKFilter, MTRK::sequence_t = std::vector<MTRK::observation_t>]: Assertion `dt' failed.
[bayes_people_tracker-1] process has died [pid 7793, exit code -6, cmd /home/strands/ferdi_ws/devel/lib/bayes_people_tracker/bayes_people_tracker __name:=bayes_people_tracker __log:=/home/strands/.ros/log/f6405d78-69cb-11e4-b94a-00032d22587c/bayes_people_tracker-1.log].
log file: /home/strands/.ros/log/f6405d78-69cb-11e4-b94a-00032d22587c/bayes_people_tracker-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```

@marcobecerrap will update his leg detector and we will try it again tomorrow.

**Comment by marcobecerrap** [comment]
It's updated. I erased redundant patterns.

**Comment by cdondrup** [comment]
Can you post some example output?

**Comment by ferdianjovan** [comment]
This is the output from /leg_detector_topic

```

header: 
  seq: 4134861
  stamp: 
    secs: 1415788290
    nsecs: 945876723
  frame_id: base_laser_link
poses: 
  - 
    position: 
      x: -0.81356803962
      y: -3.04184075535
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - 
    position: 
      x: 0.141382472445
      y: -3.23274465918
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  - 
    position: 
      x: 0.401702637755
      y: 0.52135231223
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
---

```
